# .github/workflows/build.yml
name: Build Mod Jar

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # 1.16.5 Forge에 맞춰 설정

      - name: Run Gradle build
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pixelmon-random-evolution-mod
          path: build/libs/*.jar
